import React from "react";
import{createRoot}from"react-dom/client";
import"./styles.css";
import{AnnouncementInput,ExtractedAnnouncement,Post,Task,createCampusStore,extractAnnouncement,commitExtraction,createCampusRepository,initialState,loadUserProfile,saveUserProfile,relevanceForUser,UserProfile,campusDeadlines,answerCampusQuery,demoProfile}from"./domain";

const repository=createCampusRepository();
const store=createCampusStore(repository.load());

function App(){
const[tab,setTab]=React.useState("Home");
const[,refresh]=React.useState(0);
const[tasks,setTasks]=React.useState(store.getState().tasks);
const[query,setQuery]=React.useState("");
const[liked,setLiked]=React.useState<number[]>([]);
const[showCreate,setShowCreate]=React.useState(false);
const[showProfile,setShowProfile]=React.useState(false);
const[profile,setProfile]=React.useState<UserProfile>(loadUserProfile());
const[error,setError]=React.useState("");
const[copilotQuery,setCopilotQuery]=React.useState("");
const[preview,setPreview]=React.useState<ExtractedAnnouncement|null>(null);
const[form,setForm]=React.useState<AnnouncementInput>({title:"",body:"",type:"EVENT",author:"AI Club",club:"AI Club"});
const state=store.getState();
const filtered=state.posts.filter(p=>(p.title+" "+p.body+" "+p.tags.join(" ")).toLowerCase().includes(query.toLowerCase()));
const sync=()=>{repository.save(store.getState());setTasks([...store.getState().tasks]);refresh(x=>x+1)};
const toggle=(id:number)=>{store.toggleTask(id);sync()};
const submitAnnouncement=()=>{if(!form.title.trim()||!form.body.trim())return;try{setError("");setPreview(extractAnnouncement(form))}catch(e){setError(e instanceof Error?e.message:"Could not understand announcement")}};
const confirmAnnouncement=()=>{if(!preview)return;try{setError("");commitExtraction(store,preview);}catch(e){setError(e instanceof Error?e.message:"Could not connect announcement");return;}setPreview(null);setShowCreate(false);setForm({title:"",body:"",type:"EVENT",author:"AI Club",club:"AI Club"});setTab("Home");sync()};

return <div className="app">
<aside>
<div className="brand"><div className="logo">C</div><div><b>Campus OS</b><span>Your campus, connected.</span></div></div>
<nav>{[["⌂","Home"],["✦","For You"],["☷","Explore"],["✓","My Tasks"],["◈","Network"]].map(([i,n])=><button className={tab===n?"active":""} onClick={()=>setTab(n)} key={n}><Icon>{i}</Icon>{n}</button>)}</nav>
<div className="side-card"><span className="eyebrow">TODAY</span><b>{tasks.filter(t=>!t.done).length} things need attention</b><span>{tasks.filter(t=>!t.done).length} open workflow tasks</span><button onClick={()=>setTab("For You")}>Open workflow →</button></div>
<button className="profile profile-button" onClick={()=>setShowProfile(true)}><div className="avatar">{profile.name.slice(0,1).toUpperCase()}</div><div><b>{profile.name}</b><span>{profile.branch} · Year {profile.year}</span></div><span className="dots">•••</span></button>
</aside>
<main>
<header><div><span className="eyebrow">CAMPUS OPERATING SYSTEM</span><h1>{tab==="Home"?"Good evening, "+profile.name+".":tab}</h1></div><div className="header-actions"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search campus..." /></div><button className="bell">♢</button><button className="primary" onClick={()=>setShowCreate(true)}>+ Create</button></div></header>
{tab==="Home"&&<><section className="hero"><div><span className="eyebrow">PERSONALIZED CAMPUS FEED</span><h2>Everything happening around you,<br/><em>connected to what matters.</em></h2><p>Posts become events, opportunities become deadlines, and information becomes your next action.</p><button className="primary hero-action" onClick={()=>setShowCreate(true)}>Turn an announcement into a workflow →</button></div><div className="hero-orbit"><div className="orbit center">YOU</div><div className="node n1">EVENT</div><div className="node n2">TASK</div><div className="node n3">CLUB</div><div className="node n4">DEADLINE</div></div></section><DeadlineTimeline state={state}/><CampusCopilot state={state} profile={profile} query={copilotQuery} setQuery={setCopilotQuery}/><div className="grid"><section><div className="section-head"><div><span className="eyebrow">CAMPUS SIGNAL</span><h3>Latest from your campus</h3></div><button className="ghost">Filter · All</button></div>{filtered.map(p=><PostCard key={p.id} p={p} liked={liked.includes(p.id)} onLike={()=>setLiked(l=>l.includes(p.id)?l.filter(x=>x!==p.id):[...l,p.id])}/>)}</section><Workflow tasks={tasks} toggle={toggle}/></div></>}
{tab==="For You"&&<div className="page-grid"><section><div className="panel"><span className="eyebrow">PERSONALIZED FOR {profile.name.toUpperCase()}</span><h3>Why these campus signals matter</h3>{filtered.length===0?<p className="muted">No campus signals match your search or profile context.</p>:[...filtered].sort((a,b)=>relevanceForUser(b,profile).score-relevanceForUser(a,profile).score).map(p=><div className="relevance-item" key={p.id}><div><b>{p.title}</b><small>{relevanceForUser(p,profile).reasons.join(" · ")||"General campus information"}</small></div><span>{relevanceForUser(p,profile).score>0?"Relevant":"General"}</span></div>)}</div></section><Workflow tasks={tasks} toggle={toggle}/></div>}
{tab==="My Tasks"&&<div className="page-grid"><Workflow tasks={tasks} toggle={toggle}/><section className="panel"><span className="eyebrow">WHY THIS TASK EXISTS</span><h3>Tasks are connected to campus context</h3><p>Every generated task keeps a source entity so the user can understand why it exists.</p>{tasks.slice(0,4).map(t=><div className="relation" key={t.id}><b>{state.entities.find(e=>e.id===t.source)?.name||t.source}</b><span>→</span><b>task</b><span>→</span><b>{t.title}</b></div>)}</section></div>}
{tab==="Explore"&&<div className="explore">{filtered.length===0?<section className="panel"><h3>No campus signals found</h3><p className="muted">Try a different search term.</p></section>:filtered.map(p=><PostCard key={p.id} p={p} liked={liked.includes(p.id)} onLike={()=>setLiked(l=>l.includes(p.id)?l.filter(x=>x!==p.id):[...l,p.id])}/>)}</div>}
{tab==="Network"&&<Relationship state={state}/>}
</main>
{error&&<div className="error-toast" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}
{showProfile&&<ProfileEditor profile={profile} save={next=>{setProfile(next);saveUserProfile(next);setShowProfile(false)}} close={()=>setShowProfile(false)}/>}
{showCreate&&<CreateAnnouncement form={form} setForm={setForm} preview={preview} submit={submitAnnouncement} confirm={confirmAnnouncement} close={()=>{setShowCreate(false);setPreview(null)}}/>}
</div>
}

function CampusCopilot({state,profile,query,setQuery}:{state:ReturnType<typeof store.getState>;profile:UserProfile;query:string;setQuery:(value:string)=>void}){const result=query.trim()?answerCampusQuery(state,profile,query):null;return <section className="panel copilot"><div className="section-head"><div><span className="eyebrow">CAMPUS COPILOT</span><h3>Ask your campus, not the internet.</h3></div><span className="muted">Graph-grounded</span></div><p className="muted">Ask about your deadlines, tasks, events, or what matters to you. Answers come only from connected Campus OS data.</p><div className="copilot-input"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What do I need to do for the hackathon?"/><button className="primary" disabled={!query.trim()}>Ask →</button></div>{result&&<div className="copilot-answer"><b>{result.answer}</b><small>{result.reason}</small>{result.deadlines.length>0&&<div className="copilot-chips">{result.deadlines.map(d=><span key={d.entity.id}>{d.entity.name}</span>)}</div>}{result.tasks.length>0&&<div className="copilot-chips">{result.tasks.map(t=><span key={t.id}>✓ {t.title}</span>)}</div>}</div>}</section>}\n\nfunction Icon({children}:{children:React.ReactNode}){return <span className="icon">{children}</span>}

function PostCard({p,liked,onLike}:{p:Post;liked:boolean;onLike:()=>void}){return <article className="post"><div className="post-vote"><button onClick={onLike}>{liked?"▲":"△"}</button><b>{p.votes+(liked?1:0)}</b><button>▽</button></div><div className="post-main"><div className="post-top"><span className={"type "+p.type.toLowerCase()}>{p.type}</span><span>{p.club} · {p.time==="now"?"just now":p.time+" ago"}</span></div><h3>{p.title}</h3><p>{p.body}</p><div className="tags">{p.tags.map(t=><span key={t}>#{t}</span>)}</div><div className="post-bottom"><span>◌ {p.comments} comments</span>{p.deadline&&<span className="deadline">◷ Deadline {p.deadline}</span>}<button className="context">Connected to {p.linked} ↗</button></div></div></article>}

function Workflow({tasks,toggle}:{tasks:Task[];toggle:(id:number)=>void}){const done=tasks.filter(t=>t.done).length;return <section className="workflow"><div className="workflow-head"><div><span className="eyebrow">YOUR WORKFLOW</span><h3>Next actions</h3></div><span className="progress">{done}/{tasks.length}</span></div><div className="progressbar"><i style={{width:(tasks.length?done/tasks.length*100:0)+"%"}}/></div><p className="muted">Generated from connected campus information.</p>{tasks.map(t=><label className={"task "+(t.done?"done":"")} key={t.id}><input type="checkbox" checked={t.done} onChange={()=>toggle(t.id)}/><span><b>{t.title}</b><small>{t.meta}</small></span><span className="arrow">→</span></label>)}<button className="full">View full workflow</button></section>}

function Relationship({state}:{state:ReturnType<typeof store.getState>}){const event=state.entities.find(e=>e.type==="event");const [selected,setSelected]=React.useState(event?.id||state.entities[0]?.id);const entity=state.entities.find(e=>e.id===selected)||event;const links=entity?state.relationships.filter(r=>r.from===entity.id||r.to===entity.id):[];const connected=links.map(r=>r.from===entity?.id?r.to:r.from).map(id=>state.entities.find(e=>e.id===id)).filter(Boolean);const source=entity&&state.posts.find(p=>p.linked===entity.name);const entityTasks=entity?state.tasks.filter(t=>t.source===entity.id):[];return <section className="panel relation-panel"><span className="eyebrow">CAMPUS GRAPH</span><h3>One piece of information, many connections.</h3><div className="graph">{entity&&<button className="gcenter graph-node selected" onClick={()=>setSelected(entity.id)}>{entity.name}</button>}{connected.slice(0,4).map((e,i)=><button className={"gitem g"+(i+1)+" graph-node"} key={e!.id} onClick={()=>setSelected(e!.id)}>{e!.name}</button>)}<div className="gline l1"/><div className="gline l2"/><div className="gline l3"/><div className="gline l4"/></div><div className="graph-entities">{state.entities.slice(0,8).map(e=><button className={e.id===entity?.id?"graph-filter active":"graph-filter"} key={e.id} onClick={()=>setSelected(e.id)}>{e.type}: {e.name}</button>)}</div>{entity&&<div className="graph-detail"><span className="eyebrow">SELECTED ENTITY</span><h4>{entity.name}</h4><p>{entity.meta||"Campus entity"}</p><div className="relation-list">{links.map(r=>{const other=state.entities.find(e=>e.id===(r.from===entity.id?r.to:r.from));return <div key={r.from+r.relation+r.to}><b>{r.from===entity.id?entity.name:other?.name}</b><span>{r.relation.replaceAll("_"," ")}</span><b>{r.from===entity.id?other?.name:entity.name}</b></div>})}</div>{source&&<div className="source-context"><b>Source announcement</b><p>{source.title}</p><small>{source.body}</small></div>}{entityTasks.length>0&&<div className="source-context"><b>Generated actions</b>{entityTasks.map(t=><p key={t.id}>→ {t.title}</p>)}</div>}</div>}</section>}

function CreateAnnouncement({form,setForm,preview,submit,confirm,close}:{form:AnnouncementInput;setForm:React.Dispatch<React.SetStateAction<AnnouncementInput>>;preview:ExtractedAnnouncement|null;submit:()=>void;confirm:()=>void;close:()=>void}){
return <div className="modal-backdrop" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}>{!preview?<><div className="modal-head"><div><span className="eyebrow">INGEST CAMPUS INFORMATION</span><h3>Create announcement</h3></div><button className="close" onClick={close}>×</button></div><p>Paste the announcement as-is. Campus OS will identify entities, relationships, deadlines and next actions.</p><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>EVENT</option><option>OPPORTUNITY</option><option>RESOURCE</option><option>NOTICE</option><option>COMPETITION</option><option>PROJECT</option></select></label><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="24-Hour AI Hackathon — registrations are open"/></label><label>Announcement<textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="AI Club is conducting a 24-hour hackathon on October 15..."/></label><div className="form-row"><label>Source<input value={form.author} onChange={e=>setForm({...form,author:e.target.value})}/></label><label>Club / organization<input value={form.club} onChange={e=>setForm({...form,club:e.target.value})}/></label></div><button className="primary modal-action" onClick={submit} disabled={!form.title.trim()||!form.body.trim()}>Understand this announcement →</button></>:<Understanding result={preview} back={()=>setPreview(null)} confirm={confirm}/>}</div></div>
}

function Understanding({result,back,confirm}:{result:ExtractedAnnouncement;back:()=>void;confirm:()=>void}){return <><div className="modal-head"><div><span className="eyebrow">UNDERSTOOD</span><h3>Campus OS extracted this</h3></div><span className="confidence">{Math.round(result.confidence*100)}% confidence</span></div><div className="understood-grid"><div className="understood-main"><section><span className="eyebrow">ENTITIES</span><div className="chip-list">{result.entities.map(e=><span className="entity-chip" key={e.id}><b>{e.type}</b>{e.name}</span>)}</div></section><section><span className="eyebrow">RELATIONSHIPS</span>{result.relationships.map((r,i)=><div className="extraction-row" key={i}><b>{r.from}</b><span>→ {r.relation} →</span><b>{r.to}</b></div>)}</section><section><span className="eyebrow">DEADLINES & REQUIREMENTS</span>{result.deadlines.map(d=><div className="extraction-row" key={d.label+d.date}><b>{d.label}</b><span>due</span><b>{d.date}</b></div>)}{result.requirements.map(r=><div className="extraction-row" key={r}><b>Requirement</b><span>→</span><b>{r}</b></div>)}</section></div><div className="understood-side"><span className="eyebrow">GENERATED WORKFLOW</span>{result.tasks.map(t=><div className="generated-task" key={t.id}><span>✓</span><div><b>{t.title}</b><small>{t.meta}</small></div></div>)}{result.reasons.map(r=><p className="reason" key={r}>• {r}</p>)}</div></div><div className="modal-actions"><button className="ghost" onClick={back}>← Edit announcement</button><button className="primary" onClick={confirm}>Confirm & connect →</button></div></>}

createRoot(document.getElementById("root")!).render(<App/>);
function ProfileEditor({profile,save,close}:{profile:UserProfile;save:(profile:UserProfile)=>void;close:()=>void}){const [draft,setDraft]=React.useState(profile);const split=(value:string)=>value.split(",").map(x=>x.trim()).filter(Boolean);return <div className="modal-backdrop" onMouseDown={close}><div className="modal profile-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">PERSONAL CAMPUS CONTEXT</span><h3>Your workspace profile</h3></div><button className="close" onClick={close}>×</button></div><p>These fields control which campus information becomes more relevant to you.</p><label>Name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="form-row"><label>Branch<input value={draft.branch} onChange={e=>setDraft({...draft,branch:e.target.value})}/></label><label>Year<input type="number" min="1" max="8" value={draft.year} onChange={e=>setDraft({...draft,year:Number(e.target.value)})}/></label></div><label>Interests<input value={draft.interests.join(", ")} onChange={e=>setDraft({...draft,interests:split(e.target.value)})} placeholder="AI/ML, Hackathon, Development"/></label><label>Clubs<input value={draft.clubs.join(", ")} onChange={e=>setDraft({...draft,clubs:split(e.target.value)})} placeholder="AI Club, Coding Club"/></label><label>Active projects<input value={draft.activeProjects.join(", ")} onChange={e=>setDraft({...draft,activeProjects:split(e.target.value)})} placeholder="Campus OS, GAN project"/></label><div className="modal-actions"><button className="ghost" onClick={close}>Cancel</button><button className="ghost" onClick={()=>{repository.save(initialState);saveUserProfile(demoProfile);window.location.reload()}}>Reset demo</button><button className="primary" onClick={()=>save(draft)}>Save profile →</button></div></div></div>}

function DeadlineTimeline({state}:{state:ReturnType<typeof store.getState>}){const deadlines=campusDeadlines(state);return <section className="panel deadline-panel"><div className="section-head"><div><span className="eyebrow">DEADLINE INTELLIGENCE</span><h3>What needs attention</h3></div><span className="muted">{deadlines.length} connected deadline{deadlines.length===1?"":"s"}</span></div>{deadlines.length===0?<p className="muted">No connected deadlines yet.</p>:<div className="deadline-grid">{deadlines.slice(0,5).map(d=><div className={"deadline-card "+d.status} key={d.entity.id}><div><b>{d.entity.name}</b><small>{d.source?.name||"Campus"} · {d.status.replace("_"," ")}</small></div>{d.task&&<span>→ {d.task.title}</span>}</div>)}</div>}</section>}
