import React from "react";import{createRoot}from"react-dom/client";import"./styles.css";

type Post={id:number;type:string;title:string;body:string;author:string;club:string;time:string;votes:number;comments:number;tags:string[];deadline?:string;linked?:string};
type Task={id:number;title:string;meta:string;done:boolean;source:string};
const posts:Post[]=[
{id:1,type:"EVENT",title:"24-Hour AI Hackathon — registrations are open",body:"Build anything with AI. Teams of 2–4. Registration closes October 10 and idea submissions close October 13.",author:"AI Club",club:"AI Club",time:"2h",votes:128,comments:24,tags:["AI/ML","Hackathon","Teams"],deadline:"Oct 10",linked:"AI Hackathon"},
{id:2,type:"OPPORTUNITY",title:"Microsoft is opening applications for the student ambassador program",body:"Applications are open to students interested in developer communities, events and technology advocacy.",author:"Tech Society",club:"Tech Society",time:"5h",votes:91,comments:18,tags:["Career","Microsoft"],deadline:"Oct 18",linked:"Microsoft Ambassador"},
{id:3,type:"EVENT",title:"Design Club: Figma crash course this Saturday",body:"A practical two-hour session covering components, auto-layout and prototyping. Bring your laptop.",author:"Design Club",club:"Design Club",time:"1d",votes:64,comments:11,tags:["Design","Workshop"],linked:"Figma Workshop"},
{id:4,type:"RESOURCE",title:"Seniors uploaded the complete CN lab viva notes",body:"Routing, transport layer, socket programming and common viva questions in one place.",author:"B-30 Community",club:"B-30",time:"1d",votes:52,comments:9,tags:["Academics","CN"],linked:"CN Viva Notes"}];
const initialTasks:Task[]=[{id:1,title:"Register for AI Hackathon",meta:"AI Club · due Oct 10",done:false,source:"AI Hackathon"},{id:2,title:"Find 1–3 hackathon teammates",meta:"Derived from team size 2–4",done:false,source:"AI Hackathon"},{id:3,title:"Prepare hackathon idea submission",meta:"AI Club · due Oct 13",done:false,source:"AI Hackathon"},{id:4,title:"Apply for Microsoft Ambassador",meta:"Tech Society · due Oct 18",done:false,source:"Microsoft Ambassador"}];
function Icon({children}:{children:React.ReactNode}){return <span className="icon">{children}</span>}
function App(){const[tab,setTab]=React.useState("Home");const[tasks,setTasks]=React.useState(initialTasks);const[query,setQuery]=React.useState("");const[liked,setLiked]=React.useState<number[]>([]);const filtered=posts.filter(p=>(p.title+" "+p.body+" "+p.tags.join(" ")).toLowerCase().includes(query.toLowerCase()));
const toggle=(id:number)=>setTasks(t=>t.map(x=>x.id===id?{...x,done:!x.done}:x));
return <div className="app"><aside><div className="brand"><div className="logo">C</div><div><b>Campus OS</b><span>Your campus, connected.</span></div></div><nav>{[["⌂","Home"],["✦","For You"],["☷","Explore"],["✓","My Tasks"],["◈","Network"]].map(([i,n])=><button className={tab===n?"active":""} onClick={()=>setTab(n)} key={n}><Icon>{i}</Icon>{n}</button>)}</nav><div className="side-card"><span className="eyebrow">TODAY</span><b>3 things need attention</b><span>2 deadlines · 1 team task</span><button onClick={()=>setTab("For You")}>Open workflow →</button></div><div className="profile"><div className="avatar">S</div><div><b>Shiv</b><span>CSE · 2nd year</span></div><span className="dots">•••</span></div></aside><main><header><div><span className="eyebrow">CAMPUS OPERATING SYSTEM</span><h1>{tab==="Home"?"Good evening, Shiv.":tab}</h1></div><div className="header-actions"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search campus..." /></div><button className="bell">♢</button><button className="primary">+ Create</button></div></header>{tab==="Home"&&<><section className="hero"><div><span className="eyebrow">PERSONALIZED CAMPUS FEED</span><h2>Everything happening around you,<br/><em>connected to what matters.</em></h2><p>Posts become events, opportunities become deadlines, and information becomes your next action.</p></div><div className="hero-orbit"><div className="orbit center">YOU</div><div className="node n1">EVENT</div><div className="node n2">TASK</div><div className="node n3">CLUB</div><div className="node n4">DEADLINE</div></div></section><div className="grid"><section><div className="section-head"><div><span className="eyebrow">CAMPUS SIGNAL</span><h3>Latest from your campus</h3></div><button className="ghost">Filter · All</button></div>{filtered.map(p=><PostCard key={p.id} p={p} liked={liked.includes(p.id)} onLike={()=>setLiked(l=>l.includes(p.id)?l.filter(x=>x!==p.id):[...l,p.id])}/>)}</section><Workflow tasks={tasks} toggle={toggle}/></div></>}{tab==="For You"&&<div className="page-grid"><Workflow tasks={tasks} toggle={toggle}/><Relationship/></div>}{tab==="My Tasks"&&<div className="page-grid"><Workflow tasks={tasks} toggle={toggle}/><section className="panel"><span className="eyebrow">WHY THIS TASK EXISTS</span><h3>Tasks are connected to campus context</h3><p>Every task in this prototype keeps a link back to the event or opportunity that created it. This is the core Campus OS data model.</p><div className="relation"><b>AI Hackathon</b><span>→</span><b>Registration</b><span>→</span><b>Deadline</b></div><div className="relation"><b>AI Hackathon</b><span>→</span><b>Team</b><span>→</span><b>Find teammates</b></div></section></div>}{tab==="Explore"&&<div className="explore">{filtered.map(p=><PostCard key={p.id} p={p} liked={liked.includes(p.id)} onLike={()=>setLiked(l=>l.includes(p.id)?l.filter(x=>x!==p.id):[...l,p.id])}/>)}</div>}{tab==="Network"&&<Relationship/>}</main></div>}
function PostCard({p,liked,onLike}:{p:Post;liked:boolean;onLike:()=>void}){return <article className="post"><div className="post-vote"><button onClick={onLike}>{liked?"▲":"△"}</button><b>{p.votes+(liked?1:0)}</b><button>▽</button></div><div className="post-main"><div className="post-top"><span className={"type "+p.type.toLowerCase()}>{p.type}</span><span>{p.club} · {p.time} ago</span></div><h3>{p.title}</h3><p>{p.body}</p><div className="tags">{p.tags.map(t=><span key={t}>#{t}</span>)}</div><div className="post-bottom"><span>◌ {p.comments} comments</span>{p.deadline&&<span className="deadline">◷ Deadline {p.deadline}</span>}<button className="context">Connected to {p.linked} ↗</button></div></div></article>}
function Workflow({tasks,toggle}:{tasks:Task[];toggle:(id:number)=>void}){const done=tasks.filter(t=>t.done).length;return <section className="workflow"><div className="workflow-head"><div><span className="eyebrow">YOUR WORKFLOW</span><h3>Next actions</h3></div><span className="progress">{done}/{tasks.length}</span></div><div className="progressbar"><i style={{width:(done/tasks.length*100)+"%"}}/></div><p className="muted">Generated from the campus information you've interacted with.</p>{tasks.map(t=><label className={"task "+(t.done?"done":"")} key={t.id}><input type="checkbox" checked={t.done} onChange={()=>toggle(t.id)}/><span><b>{t.title}</b><small>{t.meta}</small></span><span className="arrow">→</span></label>)}<button className="full">View full workflow</button></section>}
function Relationship(){return <section className="panel relation-panel"><span className="eyebrow">CAMPUS GRAPH</span><h3>One piece of information, many connections.</h3><div className="graph"><div className="gline l1"/><div className="gline l2"/><div className="gline l3"/><div className="gline l4"/><div className="gcenter">AI<br/>HACKATHON</div><div className="gitem g1">AI Club</div><div className="gitem g2">Oct 10<br/><small>deadline</small></div><div className="gitem g3">Team 2–4</div><div className="gitem g4">3 tasks</div></div><div className="relation-list"><div><b>AI Club</b><span>organizes</span><b>Hackathon</b></div><div><b>Hackathon</b><span>has</span><b>Deadline</b></div><div><b>Hackathon</b><span>creates</span><b>Tasks</b></div></div></section>}
createRoot(document.getElementById("root")!).render(<App/>);