import React from "react";
import{canAccessSociety,societyContribution,feedbackSummary,createCampusStore}from"./domain";
import type{CampusState,CampusEvent,SocietyAnalysis,UserProfile,FeedbackRecord,FeedbackCategory}from"./domain";
type Mutate=(fn:(store:ReturnType<typeof createCampusStore>)=>void)=>void;


export function SocietyPage({state}:{state:CampusState}){
const[societyId,setSocietyId]=React.useState(state.societies[0]?.id||"");
const society=state.societies.find(s=>s.id===societyId);
if(!society)return <div className="page inner-page"><h1>No societies found.</h1></div>;
const posts=state.societyEventPosts.filter(p=>p.societyId===society.id);
const upcoming=posts.filter(p=>p.status==="upcoming");
const past=posts.filter(p=>p.status==="past");
const societyEvents=state.events.filter(e=>e.societyId===society.id);
return <div className="page inner-page public-society-page">
<div className="society-directory"><div><span className="signal-line">CAMPUS SOCIETIES</span><h1>Find your <em>people.</em></h1><p>Discover who builds each community, what it stands for and what it is doing next.</p></div><div className="public-society-tabs">{state.societies.map(s=><button className={s.id===society.id?"active":""} key={s.id} onClick={()=>setSocietyId(s.id)}>{s.name}<small>{s.genre}</small></button>)}</div></div>
<section className="society-public-hero"><div className="society-identity"><span className="signal-line">SOCIETY PROFILE</span><h2>{society.name}</h2><p>{society.description}</p><div className="society-meta-strip"><div><span>FIC</span><b>{society.fic}</b></div><div><span>GENRE</span><b>{society.genre}</b></div><div><span>MEMBERS</span><b>{society.publicMembers.length}</b></div></div></div><div className="society-xfactor"><span className="signal-line">X-FACTOR · 50 WORDS</span><p>{society.xfactor}</p></div></section>
<section className="society-public-section"><div className="public-section-head"><div><span className="signal-line">TIMELINE</span><h2>What changed. What we built.</h2></div><span>{society.timeline.length} milestones</span></div><div className="society-timeline">{society.timeline.map(item=><article key={item.id}><b>{item.date}</b><div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div></section>
<section className="society-public-section"><div className="public-section-head"><div><span className="signal-line">THE PEOPLE</span><h2>Members & positions.</h2></div><span>{society.publicMembers.length} members</span></div><div className="public-members-grid">{society.publicMembers.map(member=><article key={member.userId}><span className="member-avatar">{member.name.slice(0,1)}</span><div><b>{member.name}</b><small>{member.position}</small></div></article>)}</div></section>
<section className="society-public-section"><div className="public-section-head"><div><span className="signal-line">UPCOMING EVENTS</span><h2>Join what happens next.</h2></div><span>{upcoming.length} events</span></div>{upcoming.length?<div className="public-event-grid">{upcoming.map(post=><SocietyEventPostCard key={post.id} post={post} event={societyEvents.find(e=>e.id===post.eventId)}/>)}</div>:<div className="public-empty">No upcoming event posts yet.</div>}</section>
<section className="society-public-section"><div className="public-section-head"><div><span className="signal-line">PAST EVENTS</span><h2>What the society has done.</h2></div><span>{past.length} events</span></div>{past.length?<div className="public-event-grid">{past.map(post=><SocietyEventPostCard key={post.id} post={post} event={state.events.find(e=>e.id===post.eventId)}/>)}</div>:<div className="public-empty">Past event records will appear here.</div>}</section>
</div>
}

function SocietyEventPostCard({post,event}:{post:import("./domain").SocietyEventPost;event:CampusEvent|undefined}){
return <article className={"society-post-card "+post.status}>
{post.media[0]&&<div className="society-post-media"><img src={post.media[0]} alt="" loading="lazy"/></div>}
<div className="society-post-body"><div className="society-post-kicker"><span>{post.status==="upcoming"?"UPCOMING EVENT":"PAST EVENT"}</span><span>POSTED BY {post.postedBy.toUpperCase()}</span></div><h3>{post.title}</h3>{event&&<div className="society-post-date">{event.date} · {event.venue}</div>}{post.description&&<p>{post.description}</p>}<div className="society-post-grid"><div><span>X-FACTOR</span><b>{post.xfactor}</b></div>{post.prizes&&<div><span>PRIZES</span><b>{post.prizes}</b></div>}{post.specialGuests.length>0&&<div><span>SPECIAL GUESTS</span><b>{post.specialGuests.join(", ")}</b></div>}{post.winners.length>0&&<div><span>WINNERS</span><b>{post.winners.join(", ")}</b></div>}</div>{post.collaboratingSocieties.length>0&&<div className="society-collabs"><span>COLLABORATION</span><b>{post.collaboratingSocieties.join(" · ")}</b></div>}{post.joinReason&&post.status==="upcoming"&&<div className="join-reason"><span>WHY JOIN</span><p>{post.joinReason}</p></div>}<div className="society-post-actions">{post.registrationLink&&post.status==="upcoming"&&<a href={post.registrationLink} target="_blank" rel="noreferrer">REGISTER ↗</a>}<span>{post.status==="past"?"ARCHIVE":"EVENT POST"}</span></div></div>
</article>
}

export function EventsPage({state,mutate}:{state:CampusState;mutate:Mutate}){
const[editing,setEditing]=React.useState<CampusEvent|null>(null);
const[showForm,setShowForm]=React.useState(false);
const empty:CampusEvent={id:"",name:"",societyId:"",societyName:"",date:"",nature:"",highlight:"",specialGuests:[],progress:0,venue:"",deadline:"",eligibility:"",status:"upcoming"};
return <div className="page inner-page events-page"><div className="page-intro"><div><span className="signal-line">CAMPUS EVENT DATABASE</span><h1>Everything happening, <em>structured.</em></h1><p>A Notion-style public event index. Society operations stay behind the private workspace.</p></div><button className="create-button" onClick={()=>{setEditing({...empty});setShowForm(true)}}>+ NEW EVENT</button></div>
<div className="database-shell"><div className="database-toolbar"><span>{state.events.length} EVENTS</span><span>PUBLIC INDEX</span><span>DEADLINES VISIBLE</span></div><div className="event-table"><div className="event-row event-head"><span>EVENT</span><span>SOCIETY</span><span>DATE</span><span>NATURE / HIGHLIGHT</span><span>SPECIAL GUESTS</span><span>PROGRESS</span><span>VENUE</span><span>DEADLINE</span><span>ELIGIBILITY</span><span>ACTIONS</span></div>{state.events.map(event=><div className="event-row" key={event.id}><div><b>{event.name}</b><small>{event.status.replace("_"," ")}</small></div><span>{event.societyName}</span><span>{event.date}</span><span><b>{event.nature}</b><small>{event.highlight}</small></span><span>{event.specialGuests.length?event.specialGuests.join(", "):"—"}</span><span><div className="progress-mini"><i style={{width:event.progress+"%"}}/></div><small>{event.progress}%</small></span><span>{event.venue||"TBD"}</span><span>{event.deadline||"—"}</span><span>{event.eligibility||"Open"}</span><div className="event-actions"><button onClick={()=>{setEditing(event);setShowForm(true)}}>EDIT</button><button onClick={()=>mutate(store=>store.removeEvent(event.id))}>DELETE</button></div></div>)}</div></div>{showForm&&editing&&<EventEditor event={editing} save={event=>mutate(store=>store.addEvent(event))} close={()=>setShowForm(false)}/>}</div>
}

function EventEditor({event,save,close}:{event:CampusEvent;save:(e:CampusEvent)=>void;close:()=>void}){
const[draft,setDraft]=React.useState(event);
const split=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
return <div className="modal-backdrop" onMouseDown={close}><div className="modal event-editor" onMouseDown={e=>e.stopPropagation()}><div className="modal-top"><div><span className="signal-line">EVENT DATABASE</span><h2>{event.id?"Edit event.":"Create event."}</h2><p>Public event information only. Private operational data belongs in Society Ops.</p></div><button onClick={close}>×</button></div><div className="form-grid"><label>EVENT NAME<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>SOCIETY<input value={draft.societyName} onChange={e=>setDraft({...draft,societyName:e.target.value,societyId:slug(e.target.value)})}/></label></div><div className="form-grid"><label>DATE<input value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>NATURE<input value={draft.nature} onChange={e=>setDraft({...draft,nature:e.target.value})}/></label></div><label>HIGHLIGHT<textarea value={draft.highlight} onChange={e=>setDraft({...draft,highlight:e.target.value})}/></label><div className="form-grid"><label>SPECIAL GUESTS<input value={draft.specialGuests.join(", ")} onChange={e=>setDraft({...draft,specialGuests:split(e.target.value)})}/></label><label>VENUE<input value={draft.venue} onChange={e=>setDraft({...draft,venue:e.target.value})}/></label></div><div className="form-grid"><label>DEADLINE<input value={draft.deadline} onChange={e=>setDraft({...draft,deadline:e.target.value})}/></label><label>ELIGIBILITY<input value={draft.eligibility} onChange={e=>setDraft({...draft,eligibility:e.target.value})}/></label></div><div className="form-grid"><label>PROGRESS %<input type="number" min="0" max="100" value={draft.progress} onChange={e=>setDraft({...draft,progress:Math.max(0,Math.min(100,Number(e.target.value)))})}/></label><label>STATUS<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as "upcoming"|"in_progress"|"completed"|"cancelled"})}><option value="upcoming">Upcoming</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label></div><div className="modal-actions"><button className="text-button" onClick={close}>Cancel</button><button className="create-button" onClick={()=>{save({...draft,id:draft.id||"event-"+Date.now()});close()}}>SAVE EVENT ↗</button></div></div></div>
}

export function SocietyOpsPage({state,profile,mutate}:{state:CampusState;profile:UserProfile;mutate:Mutate}){
const[societyId,setSocietyId]=React.useState(state.societies[0]?.id||"");
const society=state.societies.find(s=>s.id===societyId);
const access=society?canAccessSociety(state,society.id,profile.id):false;
const events=state.events.filter(e=>e.societyId===societyId);
const[eventId,setEventId]=React.useState(events[0]?.id||"");
React.useEffect(()=>{if(!events.some(e=>e.id===eventId))setEventId(events[0]?.id||"")},[societyId,state.events.length]);
if(!society)return <div className="page inner-page"><div className="page-intro"><h1>No society workspace.</h1></div></div>;
return <div className="page inner-page society-page"><div className="page-intro"><div><span className="signal-line">PRIVATE SOCIETY WORKSPACE</span><h1>{society.name} <em>operations.</em></h1><p>{society.description} This page is separate from the public event database.</p></div><span className={"private-badge "+(access?"unlocked":"locked")}>{access?"PRIVATE ACCESS GRANTED":"PRIVATE ACCESS REQUIRED"}</span></div>
<div className="society-switcher">{state.societies.map(s=><button className={s.id===societyId?"active":""} key={s.id} onClick={()=>setSocietyId(s.id)}>{s.name}<small>{state.memberships.find(m=>m.societyId===s.id&&m.userId===profile.id)?.role||"no access"}</small></button>)}</div>
{!access?<div className="locked-panel"><b>This society workspace is private.</b><p>Your current local profile is not a member of this society. In a production deployment this boundary must be enforced by server-side authentication and authorization.</p></div>:<><div className="society-event-tabs">{events.map(e=><button className={e.id===eventId?"active":""} key={e.id} onClick={()=>setEventId(e.id)}>{e.name}<small>{e.progress}% complete</small></button>)}</div>{eventId&&<SocietyEventWorkspace state={state} societyId={societyId} eventId={eventId} mutate={mutate}/>}</>}</div>
}

function SocietyEventWorkspace({state,societyId,eventId,mutate}:{state:CampusState;societyId:string;eventId:string;mutate:Mutate}){
const event=state.events.find(e=>e.id===eventId)!;
const tasks=state.societyTasks.filter(t=>t.eventId===eventId);
const budget=state.budgets.find(b=>b.eventId===eventId)||{eventId,societyId,estimated:0,actual:0,sponsorship:0,currency:"INR"};
const promos=state.promotions.filter(p=>p.eventId===eventId);
const reqs=state.requirements.filter(r=>r.eventId===eventId);
const analysis=state.analyses.find(a=>a.eventId===eventId);
const contributions=societyContribution(state,societyId,eventId);
const summary=feedbackSummary(state,societyId,eventId);
const[showAnalysis,setShowAnalysis]=React.useState(false);
return <div className="society-workspace"><section className="ops-section"><OpsHeader kicker="EVENT TASKS" title="Work to be done" meta={tasks.filter(t=>t.done).length+"/"+tasks.length+" done"}/><div className="ops-table">{tasks.map(t=><div className={"ops-row "+(t.done?"done":"")} key={t.id}><button className="check-control" onClick={()=>mutate(store=>store.addSocietyTask({...t,done:!t.done}))}>{t.done?"✓":"○"}</button><div><b>{t.title}</b><small>{t.role.toUpperCase()} · due {t.dueDate} · {t.priority}</small></div><span>{t.assignee}</span></div>)}</div></section>
<section className="ops-grid"><OpsMetric title="BUDGET" value={"₹"+budget.actual.toLocaleString("en-IN")} sub={"estimate ₹"+budget.estimated.toLocaleString("en-IN")+" · sponsorship ₹"+budget.sponsorship.toLocaleString("en-IN")}/><OpsMetric title="EVENT PROGRESS" value={event.progress+"%"} sub={event.date+" · "+event.venue}/><OpsMetric title="OPEN TASKS" value={String(tasks.filter(t=>!t.done).length)} sub="across members and leads"/></section>
<section className="ops-section"><OpsHeader kicker="CONTRIBUTION" title="Member contribution" meta="task completion"/><div className="contribution-list">{contributions.map(c=><div className="contribution-row" key={c.member}><span>{c.member}</span><div className="contribution-bar"><i style={{width:c.completion+"%"}}/></div><b>{c.completed}/{c.tasks}</b></div>)}</div></section>
<section className="ops-section"><OpsHeader kicker="PROMOTION TRACKER" title="Promotion" meta={promos.length+" channels"}/><div className="ops-cards">{promos.map(p=><div className="ops-card" key={p.id}><small>{p.channel}</small><b>{p.status.replace("_"," ")}</b><p>{p.owner} · {p.plannedDate}</p></div>)}</div></section>
<section className="ops-section"><OpsHeader kicker="RESOURCES / REQUIREMENTS" title="What the event needs" meta={reqs.filter(r=>r.status==="confirmed"||r.status==="done").length+"/"+reqs.length+" confirmed"}/><div className="ops-cards">{reqs.map(r=><div className="ops-card" key={r.id}><small>{r.category}</small><b>{r.item}</b><p>{r.quantity} · {r.owner} · {r.status}</p></div>)}</div></section>
<section className="ops-section budget-section"><OpsHeader kicker="BUDGET TRACKER" title="Money in / money out" meta={budget.currency}/><div className="budget-grid"><BudgetField label="ESTIMATED" value={budget.estimated} save={v=>mutate(store=>store.addBudget({...budget,estimated:v}))}/><BudgetField label="ACTUAL EXPENDITURE" value={budget.actual} save={v=>mutate(store=>store.addBudget({...budget,actual:v}))}/><BudgetField label="SPONSORSHIP RECEIVED" value={budget.sponsorship} save={v=>mutate(store=>store.addBudget({...budget,sponsorship:v}))}/></div></section>
<section className="ops-section"><OpsHeader kicker="POST-EVENT ANALYSIS" title={analysis?"Analysis recorded":"Close the loop"} meta={analysis?analysis.attendees+" attendees":"not recorded"}/><button className="outline-button" onClick={()=>setShowAnalysis(true)}>{analysis?"EDIT ANALYSIS":"ADD EVENT ANALYSIS"} ↗</button>{analysis&&<div className="analysis-summary"><span>{analysis.registrations} registrations</span><span>{analysis.attendees} attendees</span><span>{analysis.winners.length} winners</span><span>₹{analysis.finalExpenditure.toLocaleString("en-IN")} final spend</span></div>}</section>
<section className="ops-section"><OpsHeader kicker="FEEDBACK" title="Categorical suggestions" meta={summary.length+" categories with feedback"}/><div className="feedback-summary">{summary.map(s=><span key={s.category}>{s.category+": "+s.count+(s.negative?" · "+s.negative+" negative":"")}</span>)}</div></section>
{showAnalysis&&<AnalysisEditor eventId={eventId} existing={analysis} save={a=>mutate(store=>store.addAnalysis(a))} close={()=>setShowAnalysis(false)}/>}</div>
}

function OpsHeader({kicker,title,meta}:{kicker:string;title:string;meta:string}){return <div className="ops-header"><div><span>{kicker}</span><h2>{title}</h2></div><b>{meta}</b></div>}
function OpsMetric({title,value,sub}:{title:string;value:string;sub:string}){return <article className="ops-metric"><span>{title}</span><b>{value}</b><small>{sub}</small></article>}
function BudgetField({label,value,save}:{label:string;value:number;save:(v:number)=>void}){const[v,setV]=React.useState(String(value));return <label className="budget-field"><span>{label}</span><input type="number" value={v} onChange={e=>setV(e.target.value)} onBlur={()=>save(Number(v)||0)}/></label>}

function AnalysisEditor({eventId,existing,save,close}:{eventId:string;existing?:SocietyAnalysis;save:(a:SocietyAnalysis)=>void;close:()=>void}){
const blank:SocietyAnalysis={eventId,registrations:0,attendees:0,winners:[],participantFeedback:[],guestFeedback:[],whatWentWell:[],problems:[],suggestions:[],finalExpenditure:0,photos:[],sponsors:[],eventReport:""};
const[draft,setDraft]=React.useState<SocietyAnalysis>(existing||blank);
const lines=(v:string)=>v.split("\n").map(x=>x.trim()).filter(Boolean);
return <div className="modal-backdrop" onMouseDown={close}><div className="modal analysis-editor" onMouseDown={e=>e.stopPropagation()}><div className="modal-top"><div><span className="signal-line">POST-EVENT ANALYSIS</span><h2>Record what happened.</h2><p>Keep the event report structured so the next team can learn from it.</p></div><button onClick={close}>×</button></div><div className="form-grid"><label>REGISTRATIONS<input type="number" value={draft.registrations} onChange={e=>setDraft({...draft,registrations:Number(e.target.value)})}/></label><label>ATTENDEES<input type="number" value={draft.attendees} onChange={e=>setDraft({...draft,attendees:Number(e.target.value)})}/></label></div><label>WINNERS<input value={draft.winners.join(", ")} onChange={e=>setDraft({...draft,winners:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><div className="form-grid"><label>FINAL EXPENDITURE<input type="number" value={draft.finalExpenditure} onChange={e=>setDraft({...draft,finalExpenditure:Number(e.target.value)})}/></label><label>SPONSORS<input value={draft.sponsors.join(", ")} onChange={e=>setDraft({...draft,sponsors:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label></div><label>PHOTOS / LINKS<input value={draft.photos.join(", ")} onChange={e=>setDraft({...draft,photos:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><label>PARTICIPANT FEEDBACK<textarea value={draft.participantFeedback.join("\\n")} onChange={e=>setDraft({...draft,participantFeedback:lines(e.target.value)})}/></label><label>GUEST FEEDBACK<textarea value={draft.guestFeedback.join("\\n")} onChange={e=>setDraft({...draft,guestFeedback:lines(e.target.value)})}/></label><div className="form-grid"><label>WHAT WENT WELL<textarea value={draft.whatWentWell.join("\\n")} onChange={e=>setDraft({...draft,whatWentWell:lines(e.target.value)})}/></label><label>PROBLEMS FACED<textarea value={draft.problems.join("\\n")} onChange={e=>setDraft({...draft,problems:lines(e.target.value)})}/></label></div><div className="form-grid"><label>SUGGESTIONS<textarea value={draft.suggestions.join("\\n")} onChange={e=>setDraft({...draft,suggestions:lines(e.target.value)})}/></label><label>EVENT REPORT<textarea value={draft.eventReport} onChange={e=>setDraft({...draft,eventReport:e.target.value})}/></label></div><div className="modal-actions"><button className="text-button" onClick={close}>Cancel</button><button className="create-button" onClick={()=>{save(draft);close()}}>SAVE ANALYSIS ↗</button></div></div></div>
}

export function FeedbackPage({state,profile,mutate}:{state:CampusState;profile:UserProfile;mutate:Mutate}){
const[category,setCategory]=React.useState<FeedbackCategory>("event");
const[priority,setPriority]=React.useState<FeedbackRecord["priority"]>("medium");
const[sentiment,setSentiment]=React.useState<FeedbackRecord["sentiment"]>("neutral");
const[text,setText]=React.useState("");
const[eventId,setEventId]=React.useState(state.events[0]?.id||"");
const submit=()=>{if(!text.trim())return;mutate(store=>store.addFeedback({id:"feedback-"+Date.now(),eventId:eventId||undefined,societyId:state.events.find(e=>e.id===eventId)?.societyId,category,priority,sentiment,text:text.trim(),submitter:profile.name,createdAt:new Date().toISOString()}));setText("")};
const summary=feedbackSummary(state);
return <div className="page inner-page feedback-page"><div className="page-intro"><div><span className="signal-line">FEEDBACK / SUGGESTIONS</span><h1>Turn opinions into <em>structured signal.</em></h1><p>Categorical feedback makes recurring problems visible without losing the original comment.</p></div></div><div className="feedback-layout"><section className="feedback-composer"><OpsHeader kicker="SUBMIT FEEDBACK" title="What should change?" meta="categorical"/><div className="form-grid"><label>EVENT<select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">General campus feedback</option>{state.events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>CATEGORY<select value={category} onChange={e=>setCategory(e.target.value as FeedbackCategory)}>{["event","venue","organization","promotion","content","volunteers","technical","budget","other"].map(x=><option key={x} value={x}>{x}</option>)}</select></label></div><div className="form-grid"><label>PRIORITY<select value={priority} onChange={e=>setPriority(e.target.value as FeedbackRecord["priority"])}><option>low</option><option>medium</option><option>high</option></select></label><label>SENTIMENT<select value={sentiment} onChange={e=>setSentiment(e.target.value as FeedbackRecord["sentiment"])}><option>positive</option><option>neutral</option><option>negative</option></select></label></div><label>YOUR FEEDBACK<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="What worked, what failed, or what should be improved?"/></label><div className="modal-actions"><span className="feedback-note">Saved to this local Campus OS workspace.</span><button className="create-button" onClick={submit} disabled={!text.trim()}>SUBMIT FEEDBACK ↗</button></div></section><section className="feedback-overview"><OpsHeader kicker="CATEGORY SUMMARY" title="What keeps coming up" meta={summary.reduce((n,x)=>n+x.count,0)+" records"}/>{summary.length?<div className="feedback-category-list">{summary.map(s=><div className="feedback-category-row" key={s.category}><div><b>{s.category}</b><small>{s.negative?s.negative+" negative": "no negative reports"}</small></div><strong>{s.count}</strong></div>)}</div>:<div className="empty-feedback">No feedback has been submitted yet.</div>}</section></div></div>
}

function slug(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")||"society"}
